sudo: required #user level permission
services:
  - docker

before_install:
  - docker build -t kajal/docker-react -f Dockerfile.dev . 

script:
  - docker run -e CI=true kajal/docker-react npm run test -- --coverage
