sudo: required #user level permission
services:
  - docker

before_install:
  - docker build -t kajal/docker-react -f Dockerfile.dev . 

script:
  - docker run -e CI=true kajal/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-west-2" #region
  app: "docker-react" #name of the app
  env: "Docker-env" #name of the env name
  bucket_name: 
  on: 
    branch: master #production github branch